# Generated by Django 4.1.5 on 2023-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_id_alter_bloggeraccount_blogger_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="vendoraccount", name="corousel1",),
        migrations.RemoveField(model_name="vendoraccount", name="corousel2",),
        migrations.RemoveField(model_name="vendoraccount", name="corousel3",),
        migrations.RemoveField(model_name="vendoraccount", name="corousel4",),
        migrations.RemoveField(model_name="vendoraccount", name="corousel5",),
        migrations.RemoveField(model_name="vendoraccount", name="corousel6",),
        migrations.RemoveField(model_name="vendoraccount", name="corousel7",),
        migrations.RemoveField(model_name="vendoraccount", name="corousel8",),
        migrations.RemoveField(model_name="vendoraccount", name="logo",),
        migrations.AlterField(
            model_name="account",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(name="BloggerAccount",),
    ]
