# Generated by Django 4.1.5 on 2023-01-27 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_vendoraccount_corousel1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="vendoraccount", name="shop_number",),
        migrations.AddField(
            model_name="vendoraccount",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="vendoraccount",
            name="plan",
            field=models.CharField(
                choices=[("starter", "Starter"), ("economic", "Economic")],
                default="starter",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vendoraccount",
            name="vendor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
