# Generated by Django 4.1.6 on 2023-02-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_store_delete_vendoraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='shop_add',
            new_name='address',
        ),
    ]
