# Generated by Django 4.1.6 on 2023-02-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_shop_add_store_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_Affiliate',
            new_name='is_affiliate',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_Blogger',
            new_name='is_blogger',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_Vendor',
            new_name='is_vendor',
        ),
    ]
