# Generated by Django 4.1.6 on 2023-02-18 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_startup_rename_is_affiliate_account_is_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('interests', models.JSONField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='subscripton_amount',
            new_name='credits',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='shop_name',
            new_name='startup_name',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='template',
        ),
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('seed', 'Seed'), ('revenue', 'Revenue')], default='seed', max_length=20),
        ),
    ]
