# Generated by Django 4.1.6 on 2023-02-18 10:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_mentor_about_mentor_company_mentor_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(default='', upload_to=account.models.get_uplaod_file_name),
        ),
    ]
