# Generated by Django 4.1.6 on 2023-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_mentor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='bio',
            field=models.TextField(default='nice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='charges_in',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='charges_out',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin',
            field=models.CharField(default='linkedin.com', max_length=100),
            preserve_default=False,
        ),
    ]
