# Generated by Django 4.1.6 on 2023-03-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_mentor_bio_mentor_charges_in_mentor_charges_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
