# Generated by Django 4.1.6 on 2023-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_startup_credits_mentor_meetings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='meetings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
