# Generated by Django 4.1.6 on 2023-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_mentor_bio_alter_mentor_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='meetings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
