# Generated by Django 4.1.6 on 2023-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_mentor_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='applications',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='meetings',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
