# Generated by Django 4.1.6 on 2023-05-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_mentor_applications_alter_mentor_meetings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='applications',
            new_name='application',
        ),
    ]
