# Generated by Django 4.1.6 on 2023-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_applications_mentor_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='interests',
            field=models.JSONField(blank=True, default={'skills': ['']}, null=True),
        ),
    ]
