# Generated by Django 4.1.6 on 2023-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_mentor_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('startup_name', models.CharField(max_length=150)),
            ],
        ),
    ]
