# Generated by Django 4.1.6 on 2023-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorconnect', '0005_applications_applied_to_applications_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='expectations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
