# Generated by Django 4.1.6 on 2023-05-17 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorconnect', '0006_alter_applications_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
