# Generated by Django 4.1.6 on 2023-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorconnect', '0007_applications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
