# Generated by Django 4.1.5 on 2023-01-27 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0004_remove_vendoraccount_shop_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("txn_id", models.CharField(max_length=30)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
